name: build-publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ECNManager.csproj
      - name: Publish (Release)
        run: dotnet publish ECNManager.csproj -c Release -o ./publish
      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecnmanager-publish
          path: publish/**
